import { db } from "@workspace/db";
import { scenariosTable, systemsTable, assessmentsTable, usersTable, userStatsTable } from "@workspace/db";
import bcrypt from "bcryptjs";

async function seed() {
  console.log("Seeding database...");

  // Create admin user
  const adminEmail = "admin@standoutmanager.com";
  const existing = await db.select().from(usersTable);
  if (existing.length === 0) {
    const hash = await bcrypt.hash("admin123!", 10);
    const [admin] = await db.insert(usersTable).values({
      email: adminEmail,
      passwordHash: hash,
      name: "Admin",
      role: "admin",
      tier: "premium",
      onboardingCompleted: true,
    }).returning();
    await db.insert(userStatsTable).values({ userId: admin.id });
    console.log("Admin user created:", adminEmail);
  }

  // Seed Scenarios
  const existingScenarios = await db.select().from(scenariosTable);
  if (existingScenarios.length === 0) {
    await db.insert(scenariosTable).values([
      {
        title: "Your Direct Report is Underperforming — But Everyone Loves Them",
        description: "A beloved team member has missed three deadlines and their work quality has dropped. The team adores them. You need to address it.",
        situation: `Alex has been on your team for 18 months. Everyone loves Alex — warm, collaborative, always first to celebrate teammates. But over the past six weeks, Alex has missed three important deadlines, delivered work with notable errors, and seems disengaged in meetings.\n\nYour manager asks you in a 1:1: "How's Alex doing?" You know the performance issues exist, but you also know that addressing them will be politically sensitive given how popular Alex is. What do you do?`,
        category: "Managing Performance",
        difficulty: "intermediate",
        estimatedMinutes: 10,
        tags: ["performance", "difficult conversations", "credibility"],
        isPremium: false,
        options: [
          {
            id: "a",
            text: "Tell your manager everything is fine. Handle it privately with Alex first before escalating.",
            quality: "risky",
            explanation: "This response protects you short-term but creates a trust problem with your manager. If your manager discovers the performance issues independently, you will appear either unaware or dishonest. Neither is good for your credibility.",
            brandImpact: "Risk: Your manager will question your judgment and your transparency.",
            score: 20,
          },
          {
            id: "b",
            text: "Tell your manager honestly that Alex is struggling, that you're aware of it, and that you have a plan to address it with a documented conversation this week.",
            quality: "strong",
            explanation: "This is the response of a credible, self-aware manager. You are honest, you demonstrate awareness, and you signal that you have a plan. Your manager trusts you because you are not hiding problems — you are managing them.",
            brandImpact: "Strength: You build trust as a manager who sees clearly and acts proactively.",
            score: 100,
          },
          {
            id: "c",
            text: "Deflect by praising Alex's cultural contributions and mention the performance issues briefly.",
            quality: "weak",
            explanation: "This response signals that you prioritize popularity over performance — a critical failure for a manager. Your manager will notice that you're softening the reality. It also delays a problem that will only compound.",
            brandImpact: "Risk: You signal that you lack the discipline to manage performance clearly.",
            score: 30,
          },
          {
            id: "d",
            text: "Be direct with your manager and also have an immediate corrective conversation with Alex using a documented performance improvement framework.",
            quality: "strong",
            explanation: "Excellent. This response demonstrates both upward transparency and downward accountability. You are managing in both directions — which is exactly what standout managers do.",
            brandImpact: "Strength: You build a reputation as a manager who is fair, clear, and operationally excellent.",
            score: 95,
          },
        ],
      },
      {
        title: "Your Boss Challenges Your Judgment in a Meeting",
        description: "Your manager publicly questions a decision you made in front of the broader team and senior stakeholders.",
        situation: `You're presenting a project update in a cross-functional meeting with your manager and four senior stakeholders. Mid-presentation, your manager interrupts: "I actually don't think that approach was right. We should have gone in a different direction from the start."\n\nThe room goes quiet. Everyone is looking at you. Your manager is not wrong that the approach has challenges, but they hadn't raised these concerns privately before today. How do you respond?`,
        category: "Executive Pressure",
        difficulty: "advanced",
        estimatedMinutes: 12,
        tags: ["executive presence", "conflict", "credibility"],
        isPremium: false,
        options: [
          {
            id: "a",
            text: "Immediately agree with your manager and apologize to the room for the oversight.",
            quality: "weak",
            explanation: "Immediate capitulation signals that you lack confidence and judgment. While it avoids conflict in the moment, it damages your credibility with every stakeholder in the room. They now question whether your decisions can be trusted.",
            brandImpact: "Risk: You are seen as a manager without backbone. Stakeholders will discount your future recommendations.",
            score: 15,
          },
          {
            id: "b",
            text: "Calmly acknowledge the concern, thank your manager for raising it, and propose to discuss it in a follow-up session with more detail.",
            quality: "strong",
            explanation: "This response demonstrates composure and emotional control under pressure. You are not being defensive, and you are not capitulating. You are managing the moment intelligently by creating space for a proper discussion.",
            brandImpact: "Strength: You signal calm confidence and political awareness. Stakeholders see someone who doesn't crack.",
            score: 90,
          },
          {
            id: "c",
            text: "Defend your decision firmly with data, explaining why the approach was correct.",
            quality: "acceptable",
            explanation: "Defending your position with evidence is legitimate, but in this setting it can escalate into a conflict that damages both your relationship with your manager and your optics with stakeholders. The strength of your data matters.",
            brandImpact: "Neutral to risky: If your data is strong, it can work. If not, it backfires. The public setting makes this high-stakes.",
            score: 55,
          },
          {
            id: "d",
            text: "Visibly react — look frustrated or shocked — and then defend yourself.",
            quality: "risky",
            explanation: "This is the worst possible response. A visible emotional reaction tells the entire room that you struggle with composure under pressure. Stakeholders and your manager will remember this. It undermines every other strength you have.",
            brandImpact: "Risk: You are branded as emotionally reactive. This follows you for months.",
            score: 5,
          },
        ],
      },
      {
        title: "A Peer Manager is Subtly Undermining You",
        description: "A colleague at the same level keeps talking over you in meetings and takes credit for collaborative work.",
        situation: `Jordan, a peer manager in a neighboring function, has started a subtle campaign that is affecting your reputation. In leadership meetings, Jordan regularly talks over your points and reframes them as their own idea. After a joint project, Jordan sent an update to leadership that highlighted their team's contributions heavily while barely mentioning yours.\n\nThis isn't overt — it's subtle. But you feel it, and you suspect others notice it too. How do you handle this?`,
        category: "Peer Tension",
        difficulty: "advanced",
        estimatedMinutes: 15,
        tags: ["politics", "peer dynamics", "influence"],
        isPremium: false,
        options: [
          {
            id: "a",
            text: "Raise it directly with your manager and ask them to address it with Jordan.",
            quality: "weak",
            explanation: "Escalating to your manager without attempting to address it directly first signals immaturity and makes you appear unable to handle peer conflict. Your manager will also wonder why you didn't handle it yourself.",
            brandImpact: "Risk: You appear politically naive and unable to manage lateral relationships.",
            score: 25,
          },
          {
            id: "b",
            text: "Address it directly with Jordan in a private, one-on-one conversation — naming the specific behaviors calmly.",
            quality: "strong",
            explanation: "This is the mature, confident response. A private conversation signals that you are capable of direct communication and that you are not threatened enough to escalate prematurely. How you frame it matters — stay specific and calm, not accusatory.",
            brandImpact: "Strength: You build a reputation as someone who handles conflict directly and professionally.",
            score: 85,
          },
          {
            id: "c",
            text: "Start being more proactively visible — send your own updates to leadership, speak up first in meetings.",
            quality: "acceptable",
            explanation: "Increasing your own visibility is smart and important, but it doesn't solve the Jordan problem. Used in isolation, it's incomplete. Combined with a direct conversation, it's effective.",
            brandImpact: "Neutral: Visibility matters, but it doesn't address the root dynamic.",
            score: 60,
          },
          {
            id: "d",
            text: "Say nothing and hope it resolves itself.",
            quality: "risky",
            explanation: "Inaction is a decision. Subtle undermining that goes unchallenged tends to escalate because it's working. Saying nothing also sends a signal to observers that you either don't notice or don't mind.",
            brandImpact: "Risk: You allow someone else to quietly shape your reputation in leadership meetings.",
            score: 10,
          },
        ],
      },
      {
        title: "A Team Member Keeps Bypassing You",
        description: "One of your direct reports regularly goes directly to your manager instead of routing things through you.",
        situation: `Marcus, one of your direct reports, has started going directly to your manager, Sarah, with updates, ideas, and requests — bypassing you entirely. You've heard about it after the fact three times in the last month. Marcus is high-performing and ambitious. Sarah seems to enjoy the direct access.\n\nThis is creating an awkward dynamic and subtly undermining your authority as Marcus's manager. How do you handle it?`,
        category: "Managing Up and Down",
        difficulty: "intermediate",
        estimatedMinutes: 10,
        tags: ["authority", "team dynamics", "upward management"],
        isPremium: false,
        options: [
          {
            id: "a",
            text: "Tell Marcus that they need to stop going to Sarah and only communicate through you.",
            quality: "weak",
            explanation: "A direct restriction like this can create resentment in a high performer and can backfire if Marcus has a good relationship with Sarah. It also looks defensive. A better approach addresses the root cause.",
            brandImpact: "Risk: You appear insecure and controlling rather than confident.",
            score: 20,
          },
          {
            id: "b",
            text: "Have an honest conversation with Marcus about your expectations for how communication flows — frame it as helping them look good, not as a restriction.",
            quality: "strong",
            explanation: "This is the thoughtful response. High performers respond better when they understand the why. Frame it as: 'I want to make sure you get credit for your ideas, and the best way to ensure that is to route them through me so I can properly advocate for you.' This gets compliance while preserving the relationship.",
            brandImpact: "Strength: You demonstrate the ability to manage performance through influence, not control.",
            score: 90,
          },
          {
            id: "c",
            text: "Speak to Sarah and ask her to redirect Marcus back to you.",
            quality: "acceptable",
            explanation: "Looping in your manager is reasonable, but only if done diplomatically and after attempting to address it with Marcus first. Going to Sarah first can make you appear unable to manage your team directly.",
            brandImpact: "Neutral: Useful as a secondary step, not a primary one.",
            score: 55,
          },
          {
            id: "d",
            text: "Increase the quality and frequency of your own updates to Sarah so that Marcus's bypasses are less impactful.",
            quality: "acceptable",
            explanation: "Smart visibility management. But this doesn't solve the structural problem — it just mitigates it. A combination of this and the direct conversation with Marcus is the complete solution.",
            brandImpact: "Positive visibility, but incomplete as a standalone strategy.",
            score: 65,
          },
        ],
      },
      {
        title: "You Inherited a Messy Team Culture",
        description: "You've stepped into a manager role where the team has low morale, low trust, and a culture of blame.",
        situation: `You've just joined as manager of a 6-person team. Within your first two weeks, you observe: team members talk over each other in meetings, two people barely communicate, one senior person openly criticizes the company in front of the team, and almost no one has had a proper 1:1 in six months.\n\nYou have pressure from leadership to deliver results quickly, but you can see the culture is broken. What is your first move?`,
        category: "Team Culture",
        difficulty: "advanced",
        estimatedMinutes: 15,
        tags: ["culture", "team dynamics", "leadership"],
        isPremium: true,
        options: [
          {
            id: "a",
            text: "Address all the cultural issues immediately in a team meeting — set clear expectations for behavior.",
            quality: "risky",
            explanation: "Moving too fast in a broken culture often backfires. Team members who don't trust you yet will see this as performative or threatening. You haven't earned the relational capital to set sweeping expectations yet.",
            brandImpact: "Risk: You appear impulsive and unaware of how trust actually gets built.",
            score: 25,
          },
          {
            id: "b",
            text: "Start with individual 1:1 conversations — listen first, diagnose the root causes, then act.",
            quality: "strong",
            explanation: "This is the disciplined response. Diagnosis before action. Individual 1:1s give you real information about what's driving the culture issues. They also begin building trust with each team member individually — the foundation of any cultural change.",
            brandImpact: "Strength: You are seen as a thoughtful, strategic leader who builds before disrupting.",
            score: 95,
          },
          {
            id: "c",
            text: "Focus entirely on delivering results for the first 90 days, and defer culture concerns.",
            quality: "weak",
            explanation: "A false dichotomy. Culture and performance are not separate. A team with broken trust will not consistently deliver results — they will protect themselves at the expense of collaboration.",
            brandImpact: "Risk: You miss the root cause of performance problems and will struggle to sustain results.",
            score: 20,
          },
          {
            id: "d",
            text: "Identify the most vocal negative influence and address their behavior directly in week one.",
            quality: "risky",
            explanation: "Moving on an individual before you understand the dynamics can make you an enemy of the team rather than a trusted leader. You might target the wrong person or misread the situation entirely without enough context.",
            brandImpact: "Risk: You appear reactive and politically unaware before you've earned the room.",
            score: 30,
          },
        ],
      },
      {
        title: "You're Seen as Too Nice — and It's Hurting Your Authority",
        description: "Feedback from peers suggests your team doesn't take you seriously because you're too agreeable.",
        situation: `In your last 360 review, three different stakeholders flagged the same theme: "Sarah is extremely likable and supportive, but team members don't seem to take her direction as seriously as they should."\n\nYou recognize the feedback has merit. You've avoided conflict to preserve relationships, you've said yes when you meant no, and you've let deadlines slide without real consequence. How do you recalibrate without swinging to the other extreme?`,
        category: "Leadership Presence",
        difficulty: "intermediate",
        estimatedMinutes: 10,
        tags: ["authority", "credibility", "presence"],
        isPremium: false,
        options: [
          {
            id: "a",
            text: "Start enforcing strict deadlines with consequences and adopt a more formal communication style.",
            quality: "risky",
            explanation: "Overcorrecting creates whiplash. If your team has experienced you as warm and agreeable, a sudden shift to formal enforcement reads as inauthentic or punitive. They will resent it and it will not fix the root problem.",
            brandImpact: "Risk: You damage the relationships you built and confuse your team about who you actually are.",
            score: 25,
          },
          {
            id: "b",
            text: "Schedule a direct conversation with your team where you acknowledge you want to be more intentional about holding standards — and be specific about what will change.",
            quality: "strong",
            explanation: "Transparency with your team about your own evolution shows maturity. When done well, it builds trust rather than damaging it. You're signaling: I've heard the feedback, I take it seriously, and I'm changing — not as punishment but as growth.",
            brandImpact: "Strength: You demonstrate the self-awareness that separates standout managers from average ones.",
            score: 85,
          },
          {
            id: "c",
            text: "Start saying no more often, in small moments — gradually shift your pattern of behavior over time.",
            quality: "strong",
            explanation: "Gradual behavioral change is sustainable and less disruptive than dramatic shifts. The key is consistency — every no that you hold to trains your team that you mean what you say.",
            brandImpact: "Strength: Consistent behavior over time rebuilds credibility without creating conflict.",
            score: 80,
          },
          {
            id: "d",
            text: "Do nothing — being liked is an asset and the feedback is overblown.",
            quality: "risky",
            explanation: "Dismissing this pattern of feedback is a form of strategic blindness. Being liked is an asset, but being liked without being respected is a career limiter. The feedback is clear and consistent — it demands a response.",
            brandImpact: "Risk: Your reputation stagnates and you eventually plateau as a leader.",
            score: 5,
          },
        ],
      },
      {
        title: "Respected for Effort but Not Seen as Strategic",
        description: "You work harder than anyone but leadership sees you as a reliable executor, not a strategic thinker.",
        situation: `You've been told multiple times that you're "one of the hardest workers" and "incredibly reliable." But when a senior leadership role opened up, you were passed over for someone who — in your view — works less hard than you. In your debrief with your manager, the feedback was: "We need someone in that role who can think more strategically about the bigger picture."\n\nYou're confused and frustrated. You deliver. Why isn't it enough?`,
        category: "Career Growth",
        difficulty: "advanced",
        estimatedMinutes: 15,
        tags: ["strategy", "executive presence", "career"],
        isPremium: true,
        options: [
          {
            id: "a",
            text: "Work even harder and take on more projects to prove your value.",
            quality: "weak",
            explanation: "More of the same won't change how leadership perceives you. The problem isn't your work ethic — they already acknowledge it. Adding more volume reinforces the pattern that defines you as an executor, not a strategist.",
            brandImpact: "Risk: You deepen the gap between your perception and the profile leadership is looking for.",
            score: 10,
          },
          {
            id: "b",
            text: "Ask your manager specifically what 'thinking more strategically' looks like in practice — and request examples of someone they see as strategic.",
            quality: "strong",
            explanation: "This is the most intelligent response. You can't fix a gap you don't fully understand. Strategic thinking is often poorly defined — getting concrete examples gives you real data to work with. It also signals self-awareness.",
            brandImpact: "Strength: You demonstrate the meta-skill of strategic feedback-seeking, which is itself a strategic behavior.",
            score: 95,
          },
          {
            id: "c",
            text: "Start contributing more opinions and ideas in meetings, even when they are outside your direct area.",
            quality: "acceptable",
            explanation: "Increasing your strategic visibility is necessary, but quality matters more than quantity. Poorly timed or uninformed contributions can backfire. The goal is to demonstrate strategic thinking, not just to look like you're doing it.",
            brandImpact: "Neutral to positive: High upside if you pick your moments and say something genuinely insightful.",
            score: 60,
          },
          {
            id: "d",
            text: "Find a mentor senior to you who is seen as strategic and ask to learn how they approach problems.",
            quality: "strong",
            explanation: "This is an underrated but highly effective move. Strategic thinking is often modeled, not taught. A senior mentor gives you access to how strategic people actually think, not just what they communicate externally.",
            brandImpact: "Strength: You signal ambition, coachability, and long-term strategic intent.",
            score: 85,
          },
        ],
      },
      {
        title: "Employee Disengagement You Can See but Can't Pinpoint",
        description: "A previously strong team member has gone quiet. They're still doing the work, but something is off.",
        situation: `Priya was one of your best team members — proactive, energetic, full of ideas. Over the past five weeks, she's stopped contributing in meetings, her email responses are minimal, and she seems to be going through the motions.\n\nShe hasn't said anything to you, and her work output is still technically acceptable. But you can sense something has shifted. You're worried about losing her. How do you approach this?`,
        category: "Employee Engagement",
        difficulty: "beginner",
        estimatedMinutes: 8,
        tags: ["engagement", "retention", "1-on-1s"],
        isPremium: false,
        options: [
          {
            id: "a",
            text: "Wait and see if it resolves itself — sometimes people just have off weeks.",
            quality: "weak",
            explanation: "Disengagement is almost never self-resolving. Waiting signals to Priya that you either don't notice or don't care — both of which accelerate her disengagement. The window to re-engage is closing.",
            brandImpact: "Risk: You lose a strong team member who needed to feel seen and didn't.",
            score: 10,
          },
          {
            id: "b",
            text: "Schedule a 1:1 where you open by naming what you've noticed — specifically and without judgment — and create space for her to speak.",
            quality: "strong",
            explanation: "This is exactly right. Naming what you've observed — without assuming or accusing — opens a door that a generic check-in might not. 'I've noticed you've been a bit quieter lately and I wanted to check in' is specific, caring, and inviting.",
            brandImpact: "Strength: You build trust as a manager who pays attention and creates safety.",
            score: 100,
          },
          {
            id: "c",
            text: "Ask another team member to find out what's going on with Priya.",
            quality: "risky",
            explanation: "Outsourcing this to a colleague is a serious misstep. It signals that you lack the confidence to address it directly, and it can damage trust if Priya finds out — which she likely will.",
            brandImpact: "Risk: You are perceived as conflict-avoidant and lacking in emotional intelligence.",
            score: 5,
          },
          {
            id: "d",
            text: "Send Priya more challenging work and opportunities to re-ignite her engagement.",
            quality: "acceptable",
            explanation: "This can work if the root cause of disengagement is under-challenge. But it can also backfire if the real issue is something else entirely — a relationship conflict, a personal situation, or frustration with the team. Diagnose first.",
            brandImpact: "Neutral: May help or may completely miss the point. Lower risk than doing nothing.",
            score: 50,
          },
        ],
      },
      {
        title: "Leadership Asks You to Project Confidence You Don't Feel",
        description: "You've been asked to present on a topic where you don't feel certain, to an audience that expects certainty.",
        situation: `You've been asked to present the team's Q3 strategy to the executive leadership team in 72 hours. The strategy is still being refined, there are open questions you haven't resolved, and your manager has told you: "They want to see confidence and clarity."\n\nYou don't feel confident. The plan has real gaps. What is your approach?`,
        category: "Executive Communication",
        difficulty: "advanced",
        estimatedMinutes: 12,
        tags: ["executive presence", "communication", "confidence"],
        isPremium: true,
        options: [
          {
            id: "a",
            text: "Project full confidence and present the strategy as complete and finalized, even where gaps exist.",
            quality: "risky",
            explanation: "Overstating certainty to a senior audience is one of the highest-risk moves you can make. Executive leaders are experienced at spotting gaps. If they discover the strategy has holes you didn't acknowledge, it destroys your credibility permanently.",
            brandImpact: "High risk: A single credibility failure with senior leadership can take years to recover from.",
            score: 10,
          },
          {
            id: "b",
            text: "Present what is decided with full confidence, and frame the open questions as 'areas we're actively resolving' with a clear timeline.",
            quality: "strong",
            explanation: "This is the masterful approach. Confidence does not mean certainty — it means owning your position clearly. You can be fully confident about what you know while being honest about what you're still working through. Senior leaders respect this honesty.",
            brandImpact: "Strength: You build credibility as someone who is rigorous, honest, and strategically self-aware.",
            score: 95,
          },
          {
            id: "c",
            text: "Ask your manager to present instead, explaining that you need more time to finalize the strategy.",
            quality: "weak",
            explanation: "Passing the opportunity signals lack of confidence in yourself — and signals to your manager that you struggle under pressure. Unless there's a genuine reason you cannot present, this is a missed development opportunity you'll regret.",
            brandImpact: "Risk: You appear to lack executive readiness, which will limit your access to future opportunities.",
            score: 15,
          },
          {
            id: "d",
            text: "Tell the executive team upfront that the strategy is still being developed and you have more questions than answers.",
            quality: "weak",
            explanation: "Complete transparency about your uncertainty will undermine confidence in the team before you've even had a chance to demonstrate your thinking. There's a difference between being honest about open questions and broadcasting that you're not ready.",
            brandImpact: "Risk: You signal unpreparedness and potentially shake confidence in your team's capacity to deliver.",
            score: 20,
          },
        ],
      },
      {
        title: "Giving Hard Feedback Without Losing Trust",
        description: "A team member needs developmental feedback that will be difficult to hear. They are sensitive and have reacted poorly in the past.",
        situation: `David, a team member you genuinely respect, has a pattern of dominating conversations and not listening to others. It's affecting team dynamics and his stakeholder relationships. He's received this feedback before from a previous manager and reacted defensively.\n\nYou need to give him this feedback now, before his next performance review cycle. How do you approach the conversation?`,
        category: "Feedback",
        difficulty: "intermediate",
        estimatedMinutes: 10,
        tags: ["feedback", "trust", "communication"],
        isPremium: false,
        options: [
          {
            id: "a",
            text: "Wait until the performance review to give the feedback — it will be more formal and less personal.",
            quality: "weak",
            explanation: "Waiting months to give behavioral feedback deprives David of the opportunity to change before it formally affects his record. It also signals to David that you avoided a hard conversation — which erodes his trust in you as a coach.",
            brandImpact: "Risk: You appear conflict-avoidant, and David misses a development window.",
            score: 15,
          },
          {
            id: "b",
            text: "Give the feedback in a 1:1 — be specific about the behavior, give a concrete example, and make clear the impact it's having. Separate the behavior from the person.",
            quality: "strong",
            explanation: "Specific, behavior-based feedback in a private setting is almost always the right approach. The key is: specific example, observable behavior, clear impact. 'In Tuesday's stakeholder call, I noticed you spoke over three people — the impact was that they stopped contributing.' This is hard to dismiss.",
            brandImpact: "Strength: You build trust as a manager who gives real feedback, not just performance review summaries.",
            score: 95,
          },
          {
            id: "c",
            text: "Give the feedback in a group setting so David can hear it from multiple voices.",
            quality: "risky",
            explanation: "Public feedback on a sensitive topic is almost never the right call. It triggers defensiveness and shame. It also demonstrates a lack of emotional intelligence and will permanently damage your relationship with David.",
            brandImpact: "Risk: David will not trust you, and other team members will note your judgment.",
            score: 5,
          },
          {
            id: "d",
            text: "Frame the feedback as a question — 'How do you think the conversation went?' — to allow David to self-diagnose.",
            quality: "acceptable",
            explanation: "Using a reflective question can work if David has the self-awareness to arrive at the insight himself. But if he doesn't, you still have to give the feedback directly. This approach works best as a warm-up to direct feedback, not a replacement for it.",
            brandImpact: "Neutral: Can facilitate insight, but doesn't replace the direct conversation.",
            score: 55,
          },
        ],
      },
      {
        title: "Being Challenged in a Meeting By Someone More Senior",
        description: "A VP publicly challenges your recommendation during a company-wide review.",
        situation: `You're presenting a budget recommendation to a company-wide leadership review. A VP you have limited relationship with says, in front of 40 people: "This recommendation doesn't make sense to me. What's the basis for this number?" Their tone is skeptical and the room is quiet.\n\nYou have solid reasoning behind the number. How do you respond?`,
        category: "Executive Presence",
        difficulty: "advanced",
        estimatedMinutes: 8,
        tags: ["executive presence", "confidence", "handling pressure"],
        isPremium: false,
        options: [
          {
            id: "a",
            text: "Immediately back down and suggest you'll revisit the number offline.",
            quality: "weak",
            explanation: "Backing down without engaging the question signals that your recommendation wasn't well-reasoned — even if it was. The VP and everyone watching will now doubt whether your numbers can be trusted.",
            brandImpact: "Risk: You appear to have low conviction in your own work under pressure.",
            score: 10,
          },
          {
            id: "b",
            text: "Stay calm, thank them for the question, and walk through your reasoning clearly and concisely.",
            quality: "strong",
            explanation: "This is the executive-ready response. Thank the question — not the challenge, but the question. It signals composure. Then walk through your reasoning. If you're right, the room will see it. If you're wrong, the clear explanation will still show good-faith thinking.",
            brandImpact: "Strength: You demonstrate executive composure and that your work stands up to scrutiny.",
            score: 95,
          },
          {
            id: "c",
            text: "Respond defensively — explain that you put a lot of work into this and are confident in it.",
            quality: "risky",
            explanation: "Defensiveness signals insecurity. Referencing how hard you worked at this is irrelevant to whether the number is right. The VP doesn't care about effort — they care about soundness.",
            brandImpact: "Risk: You appear reactive and unable to handle scrutiny without taking it personally.",
            score: 15,
          },
          {
            id: "d",
            text: "Ask the VP what specific aspect they want you to clarify, then address that directly.",
            quality: "strong",
            explanation: "Excellent. Narrowing the question before answering it shows intelligence and precision. It prevents you from over-explaining and ensures you address exactly what the VP needs to know.",
            brandImpact: "Strength: You are seen as calm, smart, and efficient under pressure.",
            score: 90,
          },
        ],
      },
      {
        title: "Managing Optics After a Visible Mistake",
        description: "A project you led went over budget and over time. Leadership is asking questions.",
        situation: `A project you managed for the past quarter came in 20% over budget and four weeks late. It wasn't your fault alone — there were vendor delays and shifting requirements — but you were the lead. Your manager is now being asked to explain what happened, and you've been asked to present a post-mortem to senior leadership.\n\nHow do you approach this post-mortem?`,
        category: "Reputation Management",
        difficulty: "intermediate",
        estimatedMinutes: 12,
        tags: ["accountability", "reputation", "recovery"],
        isPremium: true,
        options: [
          {
            id: "a",
            text: "Provide a detailed explanation of all the external factors that contributed to the failure — clearly showing it wasn't primarily your fault.",
            quality: "risky",
            explanation: "A post-mortem that focuses on blame — even toward legitimate external factors — reads as defensive and unaccountable. Senior leaders have seen this pattern many times and will discount your credibility.",
            brandImpact: "Risk: You appear unable to own outcomes, which is a critical leadership weakness.",
            score: 20,
          },
          {
            id: "b",
            text: "Own the outcome, explain what you learned, present specific changes you will implement, and share what you would do differently.",
            quality: "strong",
            explanation: "This is the response of a high-integrity leader. You own the outcome without being a martyr. You demonstrate learning. You show a path forward. This is how credibility is rebuilt and often reinforced after a failure.",
            brandImpact: "Strength: Counterintuitively, how you handle failure often builds more trust than how you handle success.",
            score: 100,
          },
          {
            id: "c",
            text: "Minimize the issue — 'these things happen in complex projects.'",
            quality: "weak",
            explanation: "Minimizing a visible failure without addressing it substantively signals low accountability and low learning. Leadership will be left wondering whether you understand the magnitude of what happened.",
            brandImpact: "Risk: You appear unaccountable and strategically unaware of how this looks.",
            score: 5,
          },
          {
            id: "d",
            text: "Present a full forensic analysis of every decision made, proving each one was rational at the time.",
            quality: "acceptable",
            explanation: "Analytical rigor is valuable but can come across as over-explaining. The goal isn't to prove you were rational — it's to show you've learned and will operate differently. Focus on the forward-looking implications more than the backward-looking justification.",
            brandImpact: "Neutral: Smart and thorough, but potentially missing the emotional intelligence component.",
            score: 60,
          },
        ],
      },
    ]);
    console.log("Scenarios seeded");
  }

  // Seed Systems
  const existingSystems = await db.select().from(systemsTable);
  if (existingSystems.length === 0) {
    await db.insert(systemsTable).values([
      {
        title: "The High-Impact 1:1 Meeting System",
        description: "A repeatable structure for running 1:1s that build trust, surface problems early, and drive consistent team performance.",
        category: "One-on-Ones",
        estimatedMinutes: 8,
        isPremium: false,
        keyPrinciples: [
          "The 1:1 is for your team member — not for your status updates",
          "Create psychological safety before you create accountability",
          "Listen more than you speak — your job is to ask, not tell",
          "Consistency beats intensity — a weekly 30-minute 1:1 beats a monthly 2-hour meeting",
        ],
        steps: [
          { order: 1, title: "Open with a personal check-in (5 min)", description: "Start with something human. 'How are you actually doing?' gives your team member permission to share what's really happening before getting to work." },
          { order: 2, title: "Their agenda first (15 min)", description: "Ask: 'What's on your mind this week?' or 'What's most important for us to cover today?' This signals the meeting is for them." },
          { order: 3, title: "Progress and blockers (10 min)", description: "Review where they are on key priorities. Ask what's blocking them — and ask specifically, 'What can I do to unblock that?'" },
          { order: 4, title: "Development and growth (5 min)", description: "At least twice a month: 'What are you trying to get better at? How can I support that?' This builds loyalty and retention." },
          { order: 5, title: "Close with a clear next step (5 min)", description: "End every 1:1 by summarizing what was committed to and by whom. 'So by next week, you're going to X and I'm going to Y.'" },
        ],
        scripts: [
          { tone: "Opening", text: "Before we get into priorities — how are you actually doing this week? Anything outside of work that's affecting your focus?" },
          { tone: "Blockers", text: "On [project] — what's the single thing that's most slowing you down right now? And is there anything I can do in the next 48 hours to change that?" },
          { tone: "Development", text: "I've noticed you've been leading more of the stakeholder calls recently. How do you feel like that's going? What do you think is working and what do you want to get sharper on?" },
          { tone: "Closing", text: "So to recap: you're going to [X] by [date], and I'm going to remove [blocker] by [date]. Does that sound right? Anything else you need from me before we close?" },
        ],
      },
      {
        title: "The Feedback Conversation Framework",
        description: "A practical system for delivering developmental and corrective feedback that lands without creating defensiveness.",
        category: "Feedback",
        estimatedMinutes: 10,
        isPremium: false,
        keyPrinciples: [
          "Feedback delayed is feedback denied — address it within 48 hours",
          "Separate the behavior from the person — attack the pattern, not the identity",
          "Be specific about observable behavior, not interpretation or intent",
          "Follow up — feedback without accountability isn't coaching, it's venting",
        ],
        steps: [
          { order: 1, title: "Set the container", description: "Request a private 1:1. Say: 'I want to share some feedback that I think will help you. Can we find 20 minutes today?'" },
          { order: 2, title: "Name the specific behavior", description: "Start with a specific, observable action: 'In [meeting] on [date], I noticed [specific behavior].' Avoid generalizations like 'you always' or 'you never.'" },
          { order: 3, title: "Describe the impact", description: "Explain the consequence of the behavior: 'The impact of that was [X] — specifically, it [caused Y / signaled Z to stakeholders / affected the team in this way]." },
          { order: 4, title: "Invite their perspective", description: "Ask: 'What was going on for you in that moment?' This shows you care about their experience and may reveal context you didn't have." },
          { order: 5, title: "Set a clear expectation", description: "Be explicit about what different looks like: 'Going forward, what I need to see is [specific behavior].' Don't leave this ambiguous." },
          { order: 6, title: "Agree on follow-up", description: "Close with a specific check-in: 'Let's revisit this in two weeks in our 1:1 and see how it's going.'" },
        ],
        scripts: [
          { tone: "Opening", text: "I want to give you some feedback that I think will be useful for your growth. I'm sharing it because I want you to be successful here — not because I'm frustrated. Can I share what I've observed?" },
          { tone: "Behavior", text: "In [the team meeting on Tuesday], I noticed that when [Maria] was speaking, you [interrupted her three times and redirected the conversation back to your point]. That's the specific pattern I want to talk about." },
          { tone: "Impact", text: "The impact of that moment was that [Maria stopped contributing for the rest of the meeting]. I also noticed [two other team members exchange a look]. The perception it creates — even unintentionally — is one of dominance rather than collaboration." },
          { tone: "Expectation", text: "What I need to see going forward is [you waiting until someone finishes speaking before responding, and occasionally building on their point before adding your own]. That small shift will significantly change how you're perceived." },
        ],
      },
      {
        title: "The Delegation Decision System",
        description: "A simple framework for deciding what to delegate, how to delegate it, and how to maintain visibility without micromanaging.",
        category: "Delegation",
        estimatedMinutes: 8,
        isPremium: false,
        keyPrinciples: [
          "If you're doing work someone on your team can do, you're not managing — you're executing",
          "Delegation is not abdication — you own the outcome, they own the execution",
          "Match the task to the team member's development level, not just their current skill set",
          "Brief clearly, check in strategically, don't check in reactively",
        ],
        steps: [
          { order: 1, title: "Assess the task", description: "Ask: Can someone on my team do this at 80% of my quality? If yes, delegate. The 20% difference is almost never worth the time you save." },
          { order: 2, title: "Match the person to the task", description: "Consider: Who has the capacity? Who needs this for their development? Who would find it meaningful?" },
          { order: 3, title: "Brief with clarity", description: "Share the outcome, not the method. 'What I need is [X result] by [date]. How you get there is up to you. Here are the constraints: [Y and Z].'" },
          { order: 4, title: "Set check-in moments in advance", description: "Before you walk away: 'Let's check in on [Wednesday] to see where you are. If you hit a blocker before then, come to me immediately.' This avoids both abandonment and micromanagement." },
          { order: 5, title: "Give credit publicly", description: "When the work is done, attribute it to your team member in stakeholder communications. This builds trust and drives ownership." },
        ],
        scripts: [
          { tone: "Diplomatic", text: "I think this project would be a great opportunity for you to build your [stakeholder management / analysis / communication] skills. Here's what success looks like: [clear outcome]. I'll check in with you on [date]. What do you need from me to get started?" },
          { tone: "Firm", text: "I need you to own [project] from kickoff to delivery. The outcome I need is [X] by [date]. Come to me with blockers only, not status updates — I'll check in on [Wednesday]. This is yours to deliver." },
          { tone: "Empathetic", text: "I know you're already busy, and I want to be direct with you: this is a priority I need you to take on. I've cleared some of your backlog to make room for it. What concerns do you have that I should know about before we proceed?" },
        ],
      },
      {
        title: "The Upward Management Playbook",
        description: "How to manage your relationship with your manager to build trust, gain autonomy, and navigate organizational politics.",
        category: "Upward Management",
        estimatedMinutes: 10,
        isPremium: false,
        keyPrinciples: [
          "Your manager is your most important stakeholder relationship — treat it that way",
          "No surprises is the golden rule — bad news early is always better than bad news late",
          "Understand what your manager is measured on — then make sure your work serves that",
          "Come with solutions, not just problems — recommendations, not reports",
        ],
        steps: [
          { order: 1, title: "Know your manager's priorities", description: "Ask directly: 'What are the two or three things that would make the biggest difference to you this quarter?' Build everything around those." },
          { order: 2, title: "Manage the information flow", description: "Keep your manager appropriately informed. Not everything — but never blindside them. Determine your cadence: weekly summaries, bi-weekly 1:1s, or an agreed update format." },
          { order: 3, title: "Surface problems early with proposed solutions", description: "When something goes wrong, bring it to your manager with: 'Here's the situation, here's my proposed response, here's what I need from you.' Never bring a problem without at least one solution." },
          { order: 4, title: "Ask for feedback proactively", description: "Don't wait for performance reviews. Ask your manager quarterly: 'On a scale of 1-10, how am I doing? What would move it from a [X] to a [X+2]?'" },
          { order: 5, title: "Make your manager look good", description: "Your manager's success is your success. Ask yourself: how can I make my manager's job easier this week? Act on it." },
        ],
        scripts: [
          { tone: "Diplomatic", text: "I want to make sure I'm focused on the right things. What are the one or two areas where you think I'm having the most impact — and where do you see the biggest opportunity for me to improve?" },
          { tone: "Firm", text: "I want to flag something that's developing: [situation]. It's not critical yet, but I wanted you to know about it early. My plan is [action]. I don't need anything from you right now, but wanted you informed." },
          { tone: "Executive Ready", text: "Quick update on [project]: we're [on track/facing a specific delay]. The one thing I need from you is [specific ask]. I'll have [deliverable] to you by [date]." },
        ],
      },
      {
        title: "The Conflict De-escalation Framework",
        description: "How to de-escalate team conflict and interpersonal tension without taking sides or creating new problems.",
        category: "Conflict",
        estimatedMinutes: 12,
        isPremium: true,
        keyPrinciples: [
          "Conflict is data — it signals something structural or interpersonal that needs addressing",
          "Your job is not to pick a side — your job is to restore function",
          "The public conflict is almost never the real conflict — diagnose what's underneath",
          "Resolution requires both parties to feel heard before they can hear each other",
        ],
        steps: [
          { order: 1, title: "Speak to each person separately first", description: "Never mediate a conflict cold. Meet with each person privately. Let them vent. Ask: 'What do you need from this situation to feel like it's resolved?' Listen more than you speak." },
          { order: 2, title: "Identify the root cause", description: "Is this about a process gap, a role overlap, a communication failure, or a genuine interpersonal problem? Your intervention depends entirely on the diagnosis." },
          { order: 3, title: "Establish shared stakes", description: "Before bringing them together, remind both parties what they share — a common goal, a shared outcome, a commitment to the team. Remind them they are on the same side." },
          { order: 4, title: "Facilitate a structured joint conversation", description: "Set the norms: 'We're here to solve the problem, not to relitigate the conflict. Each of you will have the floor without interruption. Then we'll agree on a path forward.'" },
          { order: 5, title: "Agree on a behavioral contract", description: "End with explicit commitments: 'So [Person A] is going to [X] and [Person B] is going to [Y]. I'll check in with each of you in one week to see how it's going.'" },
        ],
        scripts: [
          { tone: "Empathetic", text: "I can see this situation is frustrating, and I want you to know I'm taking it seriously. Tell me everything — what happened, how it made you feel, and what you need for this to feel resolved. I'm not here to judge, I'm here to understand." },
          { tone: "Firm", text: "I need to be direct with both of you: the current dynamic is affecting the team's performance and it has to change. I'm not here to find out who's right — I'm here to get us to a place where we can work effectively together. Both of you have a role to play in that." },
          { tone: "Diplomatically Careful", text: "I want to create a space where we can have an honest conversation about what's been happening — without judgment, and with the goal of moving forward. I'd ask that we stay focused on what we need going forward, rather than re-litigating the past." },
        ],
      },
      {
        title: "The Performance Correction System",
        description: "A structured approach to correcting underperformance before it reaches the formal review process.",
        category: "Performance Management",
        estimatedMinutes: 12,
        isPremium: true,
        keyPrinciples: [
          "The goal of performance correction is change, not punishment",
          "Document everything — informal correction without documentation creates legal and HR risk",
          "Clarity is kindness — vague feedback is not feedback, it is avoidance",
          "Performance correction conversations are difficult but not doing them is more damaging",
        ],
        steps: [
          { order: 1, title: "Diagnose before you prescribe", description: "Before having the conversation, ask yourself: Is this a skill gap, a motivation gap, or a clarity gap? The intervention is completely different for each." },
          { order: 2, title: "Have the conversation within 48 hours of the triggering event", description: "Delayed performance conversations lose specificity and appear less credible. Address it while it's fresh." },
          { order: 3, title: "Be specific and behavioral", description: "Name the exact behavior or outcome. Not 'your work quality is declining' — instead 'in the last three deliverables [X, Y, Z], the following errors were present: [A, B, C].'" },
          { order: 4, title: "Set a clear standard with a timeline", description: "Say explicitly: 'What I need to see by [date] is [specific, measurable outcome]. This is the bar.' Don't be ambiguous about what success looks like." },
          { order: 5, title: "Offer support and remove excuses", description: "Ask: 'What do you need from me to hit this? What's getting in your way?' Then actually remove those blockers — so the only variable left is the team member's choice." },
          { order: 6, title: "Document the conversation", description: "After the conversation, send a brief written summary: 'As discussed today, here is what we agreed on...' This creates a paper trail and reinforces the commitment." },
        ],
        scripts: [
          { tone: "Direct", text: "I need to give you some important feedback today. The [deliverable/behavior] we discussed [in context] did not meet the standard I need. Specifically: [example]. This isn't the first time, and I want to be clear that it needs to change." },
          { tone: "Empathetic", text: "I want to have a candid conversation because I believe you can do better than what I've been seeing. I'm not here to criticize — I'm here because I want you to succeed and right now, there's a gap between where you are and where you need to be." },
          { tone: "Firm", text: "I'm going to be direct with you: the [specific behavior/outcome] is not acceptable and it needs to change, starting now. Here's exactly what success looks like from my perspective over the next 30 days..." },
        ],
      },
      {
        title: "The Brand Equity Building System",
        description: "A proactive, intentional approach to building your professional reputation inside and outside your organization.",
        category: "Brand Building",
        estimatedMinutes: 10,
        isPremium: false,
        keyPrinciples: [
          "Your brand is built in the moments when no one is watching — and confirmed when they are",
          "Consistency is the only currency — your reputation is the average of your behaviors over time",
          "Other people's perception of you is based on the signals you send, not the intentions you have",
          "Strategic visibility is not self-promotion — it is making your contribution legible",
        ],
        steps: [
          { order: 1, title: "Define your intended brand", description: "Write down: How do you want people to describe you professionally when you're not in the room? Be specific — not 'respected and competent' but 'calm under pressure, clear communicator, trusted to execute.'" },
          { order: 2, title: "Audit your current behaviors", description: "For one week, note after every meeting and interaction: what signal did I just send? Was it consistent with my intended brand?" },
          { order: 3, title: "Identify your gap", description: "Where is your behavior inconsistent with your intended brand? Common gaps: avoiding difficult conversations when you want to be seen as direct; over-explaining when you want to be seen as decisive." },
          { order: 4, title: "Commit to three brand-building habits", description: "Choose three specific behaviors that directly reinforce your intended brand. Practice them consistently for 30 days. Track them." },
          { order: 5, title: "Manage your strategic visibility", description: "Who in your organization needs to know about your contributions? Create a simple plan: quarterly stakeholder updates, contributions in key meetings, and one external visibility move per quarter." },
        ],
        scripts: [
          { tone: "Stakeholder Update", text: "Hi [Name] — wanted to share a quick update on [project/work area]. [Two-sentence summary of accomplishment and impact]. This wouldn't have been possible without [team/colleague credit]. Happy to share more detail if it would be useful." },
          { tone: "Executive Visibility", text: "In [meeting], I wanted to flag something I've been thinking about strategically: [specific insight or recommendation]. I've done some initial thinking on [X] and believe [clear position]. I'd welcome your reaction." },
        ],
      },
      {
        title: "The Decision Hygiene Framework",
        description: "A mental model for making better decisions faster, documenting your thinking, and maintaining credibility under uncertainty.",
        category: "Decision Making",
        estimatedMinutes: 8,
        isPremium: false,
        keyPrinciples: [
          "Good decisions are not defined by good outcomes — they are defined by good process",
          "Document your reasoning, not just your conclusion — you need to be able to defend how you decided",
          "Disagree and commit — once a decision is made, execute as if it were your own",
          "Speed of decision matters — a good decision made now beats a perfect decision made too late",
        ],
        steps: [
          { order: 1, title: "Define the actual decision", description: "Before deciding anything, write down exactly what decision needs to be made. Ambiguous framing leads to ambiguous decisions. 'Should we launch in Q3 or Q4?' is a better frame than 'What should we do about the launch?'" },
          { order: 2, title: "Name your options", description: "List at least three options, including 'do nothing' and the option you initially dismissed. Expanding the option set forces better thinking." },
          { order: 3, title: "Identify the key trade-off", description: "Most decisions come down to one core trade-off. Name it explicitly: 'The core trade-off here is speed vs. quality.' This sharpens the decision." },
          { order: 4, title: "Decide and document", description: "Write a one-paragraph decision memo: What we decided, why, what we're trading off, and who was consulted. This serves as a reference if the decision is questioned later." },
          { order: 5, title: "Define a review trigger", description: "For significant decisions: 'We will revisit this decision if [specific condition] changes.' This prevents decision paralysis and builds in intellectual humility." },
        ],
        scripts: [
          { tone: "Executive Ready", text: "We made a decision on [X]. The choice was [A vs. B]. We went with [A] because [specific reason]. The trade-off we accepted is [trade-off]. If [condition] changes, we would revisit. [Name] was consulted. The decision owner is [me/name]." },
          { tone: "Diplomatic", text: "I want to walk the team through how we got to this decision so everyone understands the thinking, not just the outcome. [Walk through the options, the trade-off, and the rationale.] I'm open to feedback on the process, though the decision has been made." },
        ],
      },
      {
        title: "The Team Trust Architecture",
        description: "How to build psychological safety and high-trust team dynamics that drive retention, performance, and loyalty.",
        category: "Team Culture",
        estimatedMinutes: 10,
        isPremium: true,
        keyPrinciples: [
          "Trust is built in small moments, not grand gestures",
          "Psychological safety is not permissiveness — it is the belief that speaking up is safe",
          "Your reactions to mistakes and bad news set the tone for how much truth you will hear",
          "Fairness is perceived, not just practiced — perception management is part of the job",
        ],
        steps: [
          { order: 1, title: "Model the vulnerability you want to see", description: "Share a mistake you made, acknowledge uncertainty, or ask for feedback in a team setting. This gives your team permission to do the same." },
          { order: 2, title: "React to bad news correctly", description: "When someone brings you a problem, your first response is the test. Respond with curiosity, not blame. 'Tell me more about what happened' builds more trust than any speech you can give." },
          { order: 3, title: "Reward candor, not agreement", description: "When someone disagrees with you in a meeting, thank them for it. Explicitly. 'That's a good challenge — tell me more about your concern.' This teaches the team that disagreement is safe." },
          { order: 4, title: "Be consistent, predictable, and fair", description: "Your team is always watching how you treat people. Inconsistent treatment — even when the reasons are valid — destroys trust faster than almost anything else." },
          { order: 5, title: "Follow through on every commitment", description: "Every time you say you will do something and don't, trust erodes. Build systems to ensure you keep your commitments to your team." },
        ],
        scripts: [
          { tone: "Vulnerability Model", text: "I want to be transparent with the team about something: I made a judgment call on [X] that I would do differently in hindsight. Here's what I learned from it. I'm sharing this because I want us to be a team where it's safe to be honest about mistakes — including mine." },
          { tone: "Rewarding Candor", text: "I appreciate you pushing back on that. It's exactly the kind of thinking I want from this team. Tell me more — what specifically concerns you about this approach?" },
        ],
      },
      {
        title: "The Executive Communication Template",
        description: "A proven structure for communicating with senior leadership in a way that signals strategic thinking and command presence.",
        category: "Executive Communication",
        estimatedMinutes: 8,
        isPremium: false,
        keyPrinciples: [
          "Lead with the conclusion — executives don't have time to wait for your buildup",
          "Every communication should answer: 'So what does this mean for us?' before it is asked",
          "Brevity signals confidence — if you can't say it in 3 sentences, you don't know it well enough",
          "Distinguish between 'FYI' communications and 'I need your input' communications — never blur these",
        ],
        steps: [
          { order: 1, title: "Lead with the bottom line (BLUF)", description: "Start with your conclusion or recommendation. 'My recommendation is [X]. Here's why.' Never make an executive reverse-engineer your thinking to find the point." },
          { order: 2, title: "Provide the briefest necessary context", description: "Assume your audience is intelligent but not current on the details. Two or three sentences of relevant context is usually all that's needed." },
          { order: 3, title: "State the trade-offs", description: "Show that you've considered the other options and understand the cost of your recommendation. 'The alternative was [Y], but we rejected it because [Z].'" },
          { order: 4, title: "Make a specific ask", description: "End with clarity: 'I need your approval on [X]' or 'I'm sharing this as an FYI — no action needed.' Never end without being explicit about what you need from the recipient." },
        ],
        scripts: [
          { tone: "Executive Email", text: "Subject: Decision Needed — [Topic]\n\nBottom line: I recommend [specific recommendation].\n\nContext: [2-3 sentence background]\n\nRationale: [2-3 key reasons]\n\nAlternative considered: [Option Y] — rejected because [reason]\n\nI need your sign-off by [date]. Let me know if you want to discuss." },
          { tone: "Verbal Briefing", text: "I have a quick update on [topic] — I'll keep this to two minutes. The short answer is [conclusion]. The key reason is [1-2 points]. The one thing I need from you is [specific ask]. Any questions?" },
        ],
      },
    ]);
    console.log("Systems seeded");
  }

  // Seed Assessments
  const existingAssessments = await db.select().from(assessmentsTable);
  if (existingAssessments.length === 0) {
    await db.insert(assessmentsTable).values([
      {
        title: "Management Readiness Assessment",
        description: "Diagnose your current management capabilities across 5 key dimensions: self-awareness, communication, performance management, political intelligence, and team leadership.",
        category: "management_readiness",
        estimatedMinutes: 12,
        questions: [
          {
            id: "q1",
            text: "When a team member underperforms, your first instinct is to:",
            type: "single",
            options: [
              { id: "q1a", text: "Give them more time — maybe it's a temporary issue", value: 2 },
              { id: "q1b", text: "Have a direct conversation within 48 hours naming exactly what you observed", value: 5 },
              { id: "q1c", text: "Document it first, then decide if you need to say something", value: 3 },
              { id: "q1d", text: "Talk to HR or your manager before approaching the team member", value: 1 },
            ],
          },
          {
            id: "q2",
            text: "How often do you proactively share bad news with your manager before they ask?",
            type: "single",
            options: [
              { id: "q2a", text: "Almost never — I prefer to solve problems before escalating", value: 1 },
              { id: "q2b", text: "Sometimes — depends on how serious it is", value: 3 },
              { id: "q2c", text: "Almost always — I operate on a 'no surprises' principle", value: 5 },
              { id: "q2d", text: "I only share it if I'm asked directly", value: 2 },
            ],
          },
          {
            id: "q3",
            text: "In your last difficult feedback conversation, how specific were you about the behavior?",
            type: "single",
            options: [
              { id: "q3a", text: "I gave general feedback about attitude or performance", value: 1 },
              { id: "q3b", text: "I mentioned a specific example but was vague about the impact", value: 2 },
              { id: "q3c", text: "I named a specific behavior, gave a concrete example, and described the impact", value: 5 },
              { id: "q3d", text: "I avoided the conversation entirely", value: 0 },
            ],
          },
          {
            id: "q4",
            text: "How well do you understand the political dynamics and power structures in your organization?",
            type: "scale",
            options: [
              { id: "q4_1", text: "1 - Not at all", value: 1 },
              { id: "q4_2", text: "2", value: 2 },
              { id: "q4_3", text: "3 - Somewhat", value: 3 },
              { id: "q4_4", text: "4", value: 4 },
              { id: "q4_5", text: "5 - Very well", value: 5 },
            ],
          },
          {
            id: "q5",
            text: "When you disagree with a decision made above you, you typically:",
            type: "single",
            options: [
              { id: "q5a", text: "Say nothing and comply", value: 1 },
              { id: "q5b", text: "Express your disagreement in the meeting", value: 4 },
              { id: "q5c", text: "Express concern privately to the decision maker, then commit to the decision once made", value: 5 },
              { id: "q5d", text: "Complain about it to peers or your team", value: 0 },
            ],
          },
          {
            id: "q6",
            text: "How consistently do you run structured 1:1s with each of your direct reports?",
            type: "single",
            options: [
              { id: "q6a", text: "Rarely or never — I prefer ad hoc conversations", value: 1 },
              { id: "q6b", text: "Occasionally — maybe once or twice a month if we have time", value: 2 },
              { id: "q6c", text: "Weekly or bi-weekly with a consistent structure", value: 5 },
              { id: "q6d", text: "We have them but they don't follow a structure", value: 3 },
            ],
          },
          {
            id: "q7",
            text: "To what degree do your team members know exactly what you expect from them in terms of quality and behavior?",
            type: "scale",
            options: [
              { id: "q7_1", text: "1 - Not at all clear", value: 1 },
              { id: "q7_2", text: "2", value: 2 },
              { id: "q7_3", text: "3 - Somewhat clear", value: 3 },
              { id: "q7_4", text: "4", value: 4 },
              { id: "q7_5", text: "5 - Crystal clear", value: 5 },
            ],
          },
          {
            id: "q8",
            text: "How often do you give your team members unsolicited developmental feedback (not tied to a performance review)?",
            type: "single",
            options: [
              { id: "q8a", text: "Almost never — I wait for formal review cycles", value: 1 },
              { id: "q8b", text: "Only when there's a problem I have to address", value: 2 },
              { id: "q8c", text: "Regularly — I see it as part of my weekly management job", value: 5 },
              { id: "q8d", text: "Occasionally when it's clearly positive", value: 3 },
            ],
          },
        ],
      },
      {
        title: "Brand Equity Assessment",
        description: "Measure the strength of your professional reputation — understanding how you are currently perceived versus how you intend to be perceived.",
        category: "brand_equity",
        estimatedMinutes: 10,
        questions: [
          {
            id: "b1",
            text: "If someone in your organization were asked to describe your management style to a new colleague, how confident are you that their description would match how you see yourself?",
            type: "scale",
            options: [
              { id: "b1_1", text: "1 - Very little alignment", value: 1 },
              { id: "b1_2", text: "2", value: 2 },
              { id: "b1_3", text: "3 - Somewhat aligned", value: 3 },
              { id: "b1_4", text: "4", value: 4 },
              { id: "b1_5", text: "5 - Very aligned", value: 5 },
            ],
          },
          {
            id: "b2",
            text: "How proactively do you manage your visibility with senior stakeholders outside your direct team?",
            type: "single",
            options: [
              { id: "b2a", text: "I don't — I let my work speak for itself", value: 1 },
              { id: "b2b", text: "I do it occasionally when there's a big win", value: 2 },
              { id: "b2c", text: "I have a consistent plan for managing key stakeholder relationships", value: 5 },
              { id: "b2d", text: "I rely on my manager to communicate my contributions upward", value: 2 },
            ],
          },
          {
            id: "b3",
            text: "When you make a mistake or fail at something visible, you typically:",
            type: "single",
            options: [
              { id: "b3a", text: "Minimize it and move on quickly", value: 1 },
              { id: "b3b", text: "Privately correct it and hope no one noticed", value: 2 },
              { id: "b3c", text: "Own it directly, name what you learned, and communicate what you're doing differently", value: 5 },
              { id: "b3d", text: "Explain what went wrong and who else was involved", value: 2 },
            ],
          },
          {
            id: "b4",
            text: "How clearly have you defined what you want your professional reputation to be?",
            type: "scale",
            options: [
              { id: "b4_1", text: "1 - Not defined at all", value: 1 },
              { id: "b4_2", text: "2", value: 2 },
              { id: "b4_3", text: "3 - Somewhat defined", value: 3 },
              { id: "b4_4", text: "4", value: 4 },
              { id: "b4_5", text: "5 - Clearly defined and actively building toward it", value: 5 },
            ],
          },
          {
            id: "b5",
            text: "How often do you deliver on commitments you make to peers, your manager, and your team?",
            type: "scale",
            options: [
              { id: "b5_1", text: "1 - Rarely", value: 1 },
              { id: "b5_2", text: "2", value: 2 },
              { id: "b5_3", text: "3 - Most of the time", value: 3 },
              { id: "b5_4", text: "4", value: 4 },
              { id: "b5_5", text: "5 - Almost always — I track my commitments", value: 5 },
            ],
          },
          {
            id: "b6",
            text: "When you walk into a meeting with senior leaders, how do you feel?",
            type: "single",
            options: [
              { id: "b6a", text: "Anxious — I worry about being caught out or questioned", value: 1 },
              { id: "b6b", text: "Cautious — I tend to say less rather than more", value: 2 },
              { id: "b6c", text: "Prepared — I know my material and I feel ready to contribute", value: 4 },
              { id: "b6d", text: "Confident — I actively look for opportunities to contribute and be heard", value: 5 },
            ],
          },
        ],
      },
      {
        title: "Self-Awareness Score",
        description: "Assess how accurately you understand your own strengths, blind spots, emotional triggers, and impact on others.",
        category: "self_awareness",
        estimatedMinutes: 8,
        questions: [
          {
            id: "s1",
            text: "Have you received consistent feedback (from multiple people) in the last 12 months that surprised you?",
            type: "single",
            options: [
              { id: "s1a", text: "No — feedback is usually consistent with how I see myself", value: 5 },
              { id: "s1b", text: "Yes — and it made me realize there's a meaningful gap", value: 3 },
              { id: "s1c", text: "I haven't received enough feedback to know", value: 2 },
              { id: "s1d", text: "Yes, but I disagreed with it", value: 1 },
            ],
          },
          {
            id: "s2",
            text: "How accurately can you predict how others will react to your communication style?",
            type: "scale",
            options: [
              { id: "s2_1", text: "1 - I'm often surprised by reactions", value: 1 },
              { id: "s2_2", text: "2", value: 2 },
              { id: "s2_3", text: "3 - I'm right about half the time", value: 3 },
              { id: "s2_4", text: "4", value: 4 },
              { id: "s2_5", text: "5 - I read people and situations very accurately", value: 5 },
            ],
          },
          {
            id: "s3",
            text: "When you feel stressed or under pressure at work, what typically happens to your behavior?",
            type: "single",
            options: [
              { id: "s3a", text: "I become more controlling and less open to input", value: 2 },
              { id: "s3b", text: "I withdraw and communicate less", value: 2 },
              { id: "s3c", text: "I am aware of the pattern and actively manage it", value: 5 },
              { id: "s3d", text: "I don't notice much change in my behavior", value: 1 },
            ],
          },
          {
            id: "s4",
            text: "Can you name 3 specific behaviors that other people find difficult about you — without rationalizing or minimizing them?",
            type: "single",
            options: [
              { id: "s4a", text: "No — I'm not aware of behaviors people find difficult", value: 1 },
              { id: "s4b", text: "I can name one, maybe two", value: 3 },
              { id: "s4c", text: "Yes, I can name three specific patterns", value: 5 },
              { id: "s4d", text: "I know people have issues with me but I don't know what specifically", value: 2 },
            ],
          },
          {
            id: "s5",
            text: "How often do you actively seek out feedback from people who might have critical things to say about you?",
            type: "scale",
            options: [
              { id: "s5_1", text: "1 - Never or rarely", value: 1 },
              { id: "s5_2", text: "2", value: 2 },
              { id: "s5_3", text: "3 - Sometimes", value: 3 },
              { id: "s5_4", text: "4", value: 4 },
              { id: "s5_5", text: "5 - Regularly and intentionally", value: 5 },
            ],
          },
          {
            id: "s6",
            text: "How confident are you that your team would give you honest, candid feedback if asked?",
            type: "scale",
            options: [
              { id: "s6_1", text: "1 - They would not — they feel unsafe to do so", value: 1 },
              { id: "s6_2", text: "2", value: 2 },
              { id: "s6_3", text: "3 - Some would, some wouldn't", value: 3 },
              { id: "s6_4", text: "4", value: 4 },
              { id: "s6_5", text: "5 - Yes, I've built enough safety for honest feedback", value: 5 },
            ],
          },
        ],
      },
    ]);
    console.log("Assessments seeded");
  }

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((e) => {
  console.error("Seed error:", e);
  process.exit(1);
});
